export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

//  WOMEN PRODUCT TYPE
export const GET_WOMEN_DATA_REQUEST = "GET_WOMEN_DATA_REQUEST";
export const GET_WOMEN_DATA_SUCCESS = "GET_WOMEN_DATA_SUCCESS";
export const GET_WOMEN_DATA_FAILURE = "GET_WOMEN_DATA_FAILURE";

// MEN PRODUCT TYPE
export const GET_MEN_DATA_REQUEST = "GET_MEN_DATA_REQUEST";
export const GET_MEN_DATA_SUCCESS = "GET_MEN_DATA_SUCCESS";
export const GET_MEN_DATA_FAILURE = "GET_MEN_DATA_FAILURE";

export const GET_MENS_DATA_SINGLE_REQUEST = "GET_MENS_DATA_SINGLE_REQUEST";
export const GET_MENS_DATA_SINGLE_SUCCESS = "GET_MENS_DATA_SINGLE_SUCCESS";
export const GET_MENS_DATA_SINGLE_FAILURE = "GET_MENS_DATA_SINGLE_FAILURE";

export const GET_WOMENS_DATA_SINGLE_REQUEST = "GET_WOMENS_DATA_SINGLE_REQUEST";
export const GET_WOMENS_DATA_SINGLE_SUCCESS = "GET_WOMENS_DATA_SINGLE_SUCCESS";
export const GET_WOMENS_DATA_SINGLE_FAILURE = "GET_WOMENS_DATA_SINGLE_FAILURE";

// CART PRODUCT ITEMS

export const GET_CART_PRODUCTS_REQUEST = "GET_CART_PRODUCTS_REQUEST";
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS";
export const GET_CART_PRODUCTS_FAILURE = "GET_CART_PRODUCTS_FAILURE";

export const ADD_CART_PRODUCT_REQUEST = "ADD_CART_PRODUCT_REQUEST";
export const ADD_CART_PRODUCT_SUCCESS = "ADD_CART_PRODUCT_SUCCESS";
export const ADD_CART_PRODUCT_FAILURE = "ADD_CART_PRODUCT_FAILURE";

export const EDIT_CART_PRODUCT_REQUEST = "EDIT_CART_PRODUCT_REQUEST";
export const EDIT_CART_PRODUCT_SUCCESS = "EDIT_CART_PRODUCT_SUCCESS";
export const EDIT_CART_PRODUCT_FAILURE = "EDIT_CART_PRODUCT_FAILURE";

export const DELETE_CART_PRODUCT_REQUEST = "DELETE_CART_PRODUCT_REQUEST";
export const DELETE_CART_PRODUCT_SUCCESS = "DELETE_CART_PRODUCT_SUCCESS";
export const DELETE_CART_PRODUCT_FAILURE = "DELETE_CART_PRODUCT_FAILURE";
