export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

//  WOMEN PRODUCT TYPE
export const GET_WOMEN_DATA_REQUEST  = "GET_WOMEN_DATA_REQUEST";
export const GET_WOMEN_DATA_SUCCESS  = "GET_WOMEN_DATA_SUCCESS";
export const GET_WOMEN_DATA_FAILURE  = "GET_WOMEN_DATA_FAILURE";

// MEN PRODUCT TYPE
export const GET_MEN_DATA_REQUEST  = "GET_MEN_DATA_REQUEST";
export const GET_MEN_DATA_SUCCESS  = "GET_MEN_DATA_SUCCESS";
export const GET_MEN_DATA_FAILURE  = "GET_MEN_DATA_FAILURE";

export const GET_MENS_DATA_SINGLE_REQUEST = "GET_MENS_DATA_SINGLE_REQUEST";
export const GET_MENS_DATA_SINGLE_SUCCESS = "GET_MENS_DATA_SINGLE_SUCCESS";
export const GET_MENS_DATA_SINGLE_FAILURE = "GET_MENS_DATA_SINGLE_FAILURE";

export const GET_WOMENS_DATA_SINGLE_REQUEST = "GET_WOMENS_DATA_SINGLE_REQUEST";
export const GET_WOMENS_DATA_SINGLE_SUCCESS = "GET_WOMENS_DATA_SINGLE_SUCCESS";
export const GET_WOMENS_DATA_SINGLE_FAILURE = "GET_WOMENS_DATA_SINGLE_FAILURE";


